### ISSUE TITLE
`brew cask cleanup` has been deprecated

### ISSUE THREAD

**Issue by natedunn** [minamarkham/formation#12]
`brew cask cleanup` has been [deprecated](https://github.com/Homebrew/brew/issues/4660) and causes a breaking error. It has since just been rolled up into `brew cleanup`.

**Comment by natedunn** [comment]
Created a [pull request](https://github.com/minamarkham/formation/pull/13) (my first ever!) to fix. Hope it helps.

**Comment by minamarkham** [comment]
Fixed with #13. Thanks!
