### ISSUE TITLE
Dr Cleaner Pro Plus removed?

### ISSUE THREAD

**Issue by bantic** [minamarkham/formation#14]
I noticed the link in the README to https://www.drcleaner.com/ isn't working (503 error), and a bit of research makes it look like perhaps this app is removed from the app store for spying on users? I am not sure if the Dr Cleaner Pro Plus from the `formation` scripts is the same as the one mentioned in this article, so I might be incorrect: https://9to5mac.com/2018/09/09/additional-mac-app-store-apps-caught-stealing-and-uploading-browser-history/. I haven't yet tried running `slay` to confirm that it is not there, though.

**Comment by minamarkham** [comment]
Oh thanks for letting me know. I'm going to remove that from the script.
