### ISSUE TITLE
Encountered an error with `sh` install

### ISSUE THREAD

**Issue by sdras** [minamarkham/formation#5]
Hi Mina!
First of all, thank you so much for this wonderful tool! I think you just saved me hours. 

I had a problem installing, following the readme instructions. When I switched incidences of `sh` to `bash` everything worked as expected. Not sure if its user error on my part. I'm on a brand new MacBook Pro and using Hyper as the terminal.

Thanks! 🐝

**Comment by minamarkham** [comment]
Updated the README to be a bit more clear, Hopefully that prevents any future confusion.

Thanks!
